version: '3'

services:
  app1:
    build: ./backend
    environment:
      - APP_NAME=app1
    ports:
      - "3001:3000"

  app2:
    build: ./backend
    environment:
      - APP_NAME=app2
    ports:
      - "3002:3000"

  app3:
    build: ./backend
    environment:
      - APP_NAME=app3
    ports:
      - "3003:3000"

  nginx:
    build:
      context: ./infra
    ports:
      - "443:443"
      - "8080:8080"
    depends_on:
      - app1
      - app2
      - app3